#!/usr/bin/env Rscript

suppressPackageStartupMessages(library(data.table))

project <- "/home/zhuweiyu/codex-r/GBC_STK31_public_scRNA"
out <- file.path(project, "06_feasibility")

meta_summary <- fread(file.path(out, "metadata_summary.csv"))
gene_presence <- fread(file.path(out, "target_gene_presence.csv"))
site_counts <- fread(file.path(out, "site_category_counts.csv"))
thresholds <- fread(file.path(out, "primary_patient_threshold_sensitivity.csv"))

metric <- function(name) meta_summary[metric == name, value][1]
bool <- function(x) ifelse(x, "是", "否")

gene_rows <- paste0(
  "| ", gene_presence$gene, " | ",
  bool(gene_presence$present_in_full_counts), " | ",
  bool(gene_presence$present_in_NK_RDS), " |"
)

site_rows <- paste0("| ", site_counts$standardized_site, " | ", site_counts$n_samples, " |")
threshold_rows <- paste0(
  "| ≥", thresholds$malignant_min_cells, " | ≥", thresholds$nk_min_cells,
  " | ", thresholds$n_primary_patients, " |"
)

lines <- c(
  "# 第二阶段：公共数据下载与结构核查报告",
  "",
  "项目目录：`/home/zhuweiyu/codex-r/GBC_STK31_public_scRNA`  ",
  "完成日期：2026-08-13（服务器 UTC；北京时间同日）",
  "",
  "> 本阶段只完成下载、校验、解压、结构和标识符核查。未进行 STK31 表达分析、差异表达、相关性、NK 评分、pseudobulk、重新聚类、CellChat、富集、生存分析或任何生物学结论推断。",
  "",
  "## 1. 下载与完整性校验",
  "",
  "| 文件 | 实际大小（bytes） | MD5 | 结果 |",
  "|---|---:|---|---|",
  "| `scRNA_processed_data_all.zip` | 4,513,392,529 | `922631b810f83653b85bd479084b7a77` | 通过 |",
  "| `NK.RDS` | 591,862,106 | `2282d943cac04844c9580275945672af` | 通过 |",
  "",
  "两个文件均来自 Zenodo 15400138 官方内容端点，使用断点续传下载。原始 ZIP 和 NK.RDS 均保留在 `01_raw_data/`，未删除。",
  "",
  "## 2. 外层 ZIP 与 RAR 结构",
  "",
  "外层 ZIP 已解压至 `02_processed_data/All_single_cells/`：",
  "",
  "| 文件 | 实际大小（bytes） |",
  "|---|---:|",
  "| `GBC_counts.rar` | 4,505,225,188 |",
  "| `GBC_Metadata.txt` | 74,795,431 |",
  "| `sample_info.xlsx` | 31,042 |",
  "",
  "先执行了 `unrar l`。RAR 5 内部包含标准 10x 三件套：",
  "",
  "| RAR 内部文件 | 压缩前/归档记录大小（bytes） | 格式 |",
  "|---|---:|---|",
  "| `10X_counts/barcodes.tsv.gz` | 5,158,570 | gzip 压缩 TSV |",
  "| `10X_counts/features.tsv.gz` | 232,069 | gzip 压缩 TSV |",
  "| `10X_counts/matrix.mtx.gz` | 4,499,835,759 | gzip 压缩 Matrix Market |",
  "| 合计 | 4,505,226,398 | 稀疏 10x 格式 |",
  "",
  "RAR 内容体积相对服务器磁盘合理，已解出到 `02_processed_data/All_single_cells/counts/10X_counts/`，仍保持 gzip 压缩；没有转换成 dense matrix。",
  "",
  "Matrix Market 头为 `matrix coordinate integer general`，维度为 **32,137 genes × 1,117,245 cells**，非零条目数为 **1,457,063,953**。因此矩阵方向明确：行是基因，列是细胞。features 与 barcodes 行数分别为 32,137 和 1,117,245，与矩阵维度一致。",
  "",
  "## 3. GBC_Metadata.txt",
  "",
  paste0("- 实际细胞行数：", metric("rows_excluding_schema_row"), "（另有 1 行数据模式说明，读取时已识别并排除）。"),
  paste0("- 列数：", metric("columns"), "。"),
  "- 列名：`name`, `celltype`, `subtype`, `sample_name`。",
  paste0("- `sample_name` 唯一值：", metric("unique_sample_name"), "。"),
  paste0("- 重复 `name`：", metric("duplicated_name_rows"), "。"),
  "- metadata `name` 与 `barcodes.tsv.gz`：数量相同、无重复、集合完全相同，并且顺序完全一致，可一一对应。",
  paste0("- `Malignant epithelial cells`：", metric("malignant_epithelial_cells"), " 个。"),
  paste0("- `NK cells`：", metric("nk_cells"), " 个。"),
  paste0("- 含恶性上皮细胞的 sample：", metric("samples_with_malignant_epithelial"), " 个。"),
  paste0("- 含 NK 的 sample：", metric("samples_with_nk"), " 个。"),
  paste0("- 同时含恶性上皮和 NK 的 sample：", metric("samples_with_both_malignant_and_nk"), " 个。"),
  "",
  "完整 `celltype` 频数保存于 `celltype_counts.csv`，完整 `subtype` 频数保存于 `subtype_counts.csv`，逐样本细胞计数保存于 `sample_celltype_counts.csv`。本阶段没有检查任何基因的表达量。",
  "",
  "## 4. sample_info.xlsx 与患者/样本/站点映射",
  "",
  "工作簿包含 217 个 Sample ID、22 列。主要字段包括：`Sample ID`, `scRNA-seq`, `TNM stage`, `Histological type`, `Site`, `Liver metastasis`, `Lymph node metastasis`, `Metastatic group`, `OS_month`, `Event` 等；原表没有名为 Patient ID 的独立列。",
  "",
  "- metadata 的 135 个 `sample_name` 均与 sample_info 的 `Sample ID` 精确匹配；无法对应的 metadata 样本为 0。",
  "- sample_info 中另有 82 个没有 metadata 细胞的条目；这 82 个条目的 `scRNA-seq` 均为 `No`，因此不是当前表达矩阵缺失匹配。",
  "- 患者 ID 暂按 Sample ID 的共同前缀派生，例如 `GBC_042_P`, `GBC_042_LI`, `GBC_042_LM` 均映射为 `GBC_042`。该规则得到 102 个患者前缀；27 个患者具有多个 scRNA 样本，最多 4 个。",
  "- 是否有作者另行定义的患者编号字段：**待核实**。当前工作簿未提供独立 Patient ID 列，因此最终发表分析前应以论文方法/作者说明再次确认共同前缀规则。",
  "",
  "样本类型按 `Site` 和 `Histological type` 的实际值确定：",
  "",
  "| 标准化类型 | scRNA 样本数 |",
  "|---|---:|",
  site_rows,
  "",
  "其中 `Other` 包括非癌性 Primary（慢性/黄色肉芽肿性胆囊炎）、上皮内瘤变、PBMC 和 Primary polyp。当前 sample_info 的 `Site` 值中没有 Adjacent/NAT，因此 **Adjacent/NAT：待核实/未在表中识别到**。不能确定的值未猜测；当前实际 Site 值均已映射，没有遗留 Unknown。",
  "",
  "## 5. NK.RDS 结构",
  "",
  "- 对象类型：Seurat。",
  "- 对象版本槽：4.1.0；在服务器 Seurat 5.2.1 / SeuratObject 5.0.2 下成功读取，说明本阶段读取兼容。后续写回或升级对象前仍应另存新文件，避免覆盖原始 RDS。",
  "- 维度：31,910 features × 28,266 cells；feature 和 cell 名均无重复。",
  "- assays：`RNA`；DefaultAssay：`RNA`。",
  "- assay 类：旧式 `Assay`；可见 layers/slots：`counts`, `data`, `scale.data`。",
  "- 原始 RNA counts：存在，维度 31,910 × 28,266。",
  "- normalized data：存在，维度 31,910 × 28,266。",
  "- PCA：存在，28,266 × 50；UMAP：存在，28,266 × 2。",
  "- 图：`RNA_nn`, `RNA_snn`。",
  "- metadata：28,266 行、82 个字段；完整字段及示例见 `nk_rds_structure.txt`。",
  "- NK 亚群字段：作者字段 `celltype`，14 个亚群；另有多个聚类字段。没有修改作者注释。",
  "- 样本字段：应使用 `orig.ident`，其 133 个唯一值全部能映射到全细胞 metadata 和 sample_info。`sample.ident` 只有 65 个唯一值，不是完整样本来源字段，不建议用于患者配对。",
  "- NK.RDS 内没有显式 patient 字段，也没有显式 site/tissue 字段；需通过 `orig.ident` → sample_info 映射补齐。",
  "- NK.RDS 的 28,266 个细胞名与全细胞 metadata 中标为 NK 的 28,266 个细胞集合完全一致；顺序不同，因此使用时必须按细胞名匹配，不能按行号直接拼接。",
  "- `orig.ident` 中没有 NK 的两个全数据样本是 `GBC_047_PO` 和 `GBC_077_LM`，与 metadata 的 133 个含 NK 样本计数一致。",
  "",
  "## 6. 目标基因 feature-name 存在性",
  "",
  "本表只检查 feature names，不计算表达量、均值、阳性率或相关性。",
  "",
  "| gene | present_in_full_counts | present_in_NK_RDS |",
  "|---|---|---|",
  gene_rows,
  "",
  "结论：除 `KIR2DL2` 外，其余 21 个目标基因均存在于两套 feature names 中。`KIR2DL2` 在完整 counts 和 NK.RDS 中均不存在；这是 feature-list 事实，不等同于表达为零，也不应补值或改名。是否存在作者采用其他基因注释/同源映射：**待核实**。",
  "",
  "## 7. 恶性上皮与 NK 的安全提取方案",
  "",
  "不需要先建立完整百万细胞 Seurat 对象。推荐流程：",
  "",
  "1. 用 `data.table::fread` 读取四列 metadata。",
  "2. 因 metadata `name` 与 10x barcodes 顺序完全一致，按细胞名核对后建立列索引：恶性上皮使用 `subtype == \"Malignant epithelial cells\"`；NK 使用 `celltype == \"NK cells\"`。",
  "3. 对完整 10x Matrix Market 数据使用支持稀疏/流式或磁盘后端的读取方式，按列索引提取 96,942 个恶性上皮细胞；不要 `as.matrix()`。若常规 `Read10X()` 必须先读完整 dgCMatrix，应在本服务器上单任务运行并监测峰值内存，随后立即子集和释放完整对象。更稳妥的是使用分块/磁盘后端（例如 BPCells/HDF5 路线）或流式过滤 Matrix Market 条目。相关工具是否安装：**待核实**，本阶段未安装。",
  "4. NK 优先直接使用已验证的 `NK.RDS`，其 raw counts、normalized data、PCA/UMAP 和作者 NK 亚群均已包含；按 `orig.ident` 映射 sample_info。",
  "5. 后续 pseudobulk 必须从 raw counts 聚合，并以患者/样本为统计单位；本阶段未执行。",
  "",
  "## 8. 患者级匹配可行性",
  "",
  "- 在 sample 级，56 个 sample 同时含恶性上皮和 NK。",
  "- 按共同前缀派生患者 ID 并合并其全部组织样本时，48 个患者前缀同时具有两类细胞。此口径可能跨组织，不应直接替代同组织配对。",
  "- 严格限定 `Primary tumor` 时，86 个原发肿瘤患者前缀中有 11 个同时具有恶性上皮细胞和 NK（两者均 >0）。",
  "- “足够细胞”的最小阈值在研究方案中没有预设，因此满足“足够”的患者数：**待核实**，本阶段不擅自定义。",
  "- 为透明评估，仅输出以下原发肿瘤阈值敏感性计数；这些阈值不是预定义纳入标准：",
  "",
  "| 恶性上皮细胞下限 | NK 细胞下限 | 原发肿瘤患者数 |",
  "|---:|---:|---:|",
  threshold_rows,
  "",
  "## 9. 兼容性、磁盘和内存风险",
  "",
  "- 服务器：Ubuntu 24.04 系列内核；R 4.3.3；Seurat 5.2.1；SeuratObject 5.0.2；Matrix 1.6.5；data.table 1.17.2；readxl 1.4.4。",
  "- 内存：503 GiB 总内存，检查时约 480 GiB available；swap 8 GiB，未使用。",
  "- 磁盘：项目所在卷检查时约 534 GiB 可用。ZIP、RAR 和解出的 gzip counts 同时保留会占用约 13–14 GiB，当前空间足够。",
  "- metadata + NK 结构脚本峰值 RSS 约 2.52 GiB；标识符核查峰值约 1.75 GiB。",
  "- 最大风险是完整矩阵有 14.57 亿个非零条目。R 的 `dgCMatrix` 除压缩文件外还需大量内存存储数值和行索引；理论最低数组量级已超过约 17 GiB，实际读取、转换、复制和 Seurat 封装会更高。虽然本服务器内存足够，但不建议直接构建完整百万细胞 Seurat 对象。",
  "- Matrix 1.6.5 的稀疏矩阵索引和单向量长度限制、读取函数是否能稳定处理 14.57 亿 nnz：**待核实**。应优先分块或磁盘后端，避免内存复制。",
  "- NK.RDS 是 Seurat 4.1.0 格式对象，在 Seurat 5.2.1 中成功只读加载；后续若调用 Seurat 5 专属 layer 操作，应先在副本上验证兼容。",
  "",
  "## 10. 本阶段生成文件",
  "",
  "`06_feasibility/` 至少包含并已核验：",
  "",
  "- `metadata_summary.csv`",
  "- `celltype_counts.csv`",
  "- `sample_celltype_counts.csv`",
  "- `patient_sample_mapping.csv`",
  "- `sample_site_mapping.csv`",
  "- `target_gene_presence.csv`",
  "- `nk_rds_structure.txt`",
  "- `counts_structure.txt`",
  "- `stage2_summary.md`",
  "",
  "另生成 `subtype_counts.csv`, `nk_subtype_counts.csv`, `primary_patient_cell_counts.csv`, `primary_patient_threshold_sensitivity.csv`, `patient_sample_multiplicity.csv`, `patient_all_sites_cell_counts.csv`, `identifier_mapping_audit.txt`, `sample_info_audit.txt`, `stage2_environment.txt` 等审计文件。所有 Bash/R 脚本均保存在 `04_scripts/`。",
  "",
  "## 11. 对本阶段十个问题的明确回答",
  "",
  "1. **全细胞表达矩阵是什么格式？** 标准 10x gzip 压缩 Matrix Market 稀疏矩阵：`matrix.mtx.gz` + `features.tsv.gz` + `barcodes.tsv.gz`；32,137 genes × 1,117,245 cells。",
  "2. **如何安全读入 111 万细胞矩阵？** 不转 dense；优先分块/磁盘后端或流式按 metadata 列索引提取。若临时读为完整 dgCMatrix，只能在本服务器单任务执行并监测内存，随后立即子集和释放。",
  "3. **能否不建立完整 Seurat 就提取恶性上皮和 NK？** 能。metadata 与 barcode 顺序、集合完全一致，可按名称/列索引提取；NK 还可直接使用 NK.RDS。",
  "4. **NK.RDS 是不是 Seurat 对象？** 是。",
  "5. **NK.RDS 是否包含 raw counts？** 是。",
  "6. **NK.RDS 是否包含完整 sample/patient 信息？** 含完整可映射的 sample 字段 `orig.ident`；不含显式 patient/site 字段，需连接 sample_info。`sample.ident` 不完整，不应用于匹配。",
  "7. **恶性上皮和 NK 能否患者级匹配？** 可以通过 sample_name/orig.ident → Sample ID → 派生患者前缀匹配；但独立 Patient ID 字段和作者正式编号规则仍待核实。",
  "8. **primary tumor 中多少患者同时具有足够细胞？** 两类细胞均 >0 时为 11 个患者前缀；“足够”的阈值未定义，所以最终足够患者数待核实。敏感性表已提供。",
  "9. **目标基因是否全部存在？** 否；`KIR2DL2` 在两套 feature lists 中均不存在，其余目标基因均存在。",
  "10. **明显兼容性或内存风险？** 有：14.57 亿 nnz 不宜封装完整 Seurat；Seurat 4 对象在 Seurat 5 下读取成功但写回/升级需用副本；Matrix 大对象能力需先小规模验证。服务器硬件足够进行安全的分块/子集工作。",
  "",
  "## 12. 尚未确认的信息",
  "",
  "- 独立 Patient ID 及作者正式的患者—样本映射规则：**待核实**。",
  "- `Adjacent/NAT` 样本：sample_info 的 Site 值中未识别到，是否在其他补充资料中定义：**待核实**。",
  "- 原发肿瘤患者“足够”恶性上皮/NK细胞的预设纳入阈值：**待核实**。",
  "- `KIR2DL2` 缺失是否源于基因注释版本、同源映射或作者预处理：**待核实**。",
  "- BPCells/HDF5/其他磁盘后端是否已安装并选定：**待核实**；本阶段没有安装。",
  "- Matrix 1.6.5 对 14.57 亿 nnz 的完整内存读取稳定性：**待核实**；本阶段没有加载矩阵主体。",
  "",
  "第二阶段完成。按要求在此停止，不自动进入第三阶段。"
)

writeLines(lines, file.path(out, "stage2_summary.md"), useBytes = TRUE)
cat(paste(lines, collapse = "\n"), "\n")
